### ISSUE TITLE
Checklayer failure: gatesgarth: missing upstream dependency

### ISSUE THREAD

**Issue by rpcme** [aws/meta-aws#122]
[Container] 2021/04/02 11:29:20 Running command yocto-check-layer -d -o ycl-check.log --additional-layers meta-python --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python -d $HOME/dist/meta-aws
77 | INFO: Detected layers:
78 | INFO: meta-aws: LayerType.SOFTWARE, /root/dist/meta-aws
79 | ERROR: checklayer: Don't have conf/layer.conf file.
80 | INFO:
81 | INFO: Setting up for meta-aws(LayerType.SOFTWARE), /root/dist/meta-aws
82 | DEBUG: Processing dependencies core meta-python networking-layer openembedded-layer for layer meta-aws.
83 | DEBUG: Processing dependencies core openembedded-layer for layer meta-python.
84 | DEBUG: Processing dependencies core for layer meta-oe.
85 | DEBUG: Processing dependencies core meta-python openembedded-layer for layer meta-networking.
86 | INFO: Adding layer meta-python
87 | INFO: meta-python is already in /root/dist/meta-aws/qa/checklayer/conf/bblayers.conf
88 | INFO: Adding layer meta-oe
89 | INFO: meta-oe is already in /root/dist/meta-aws/qa/checklayer/conf/bblayers.conf
90 | INFO: Adding layer meta-networking
91 | INFO: meta-networking is already in /root/dist/meta-aws/qa/checklayer/conf/bblayers.conf
92 | DEBUG: Processing dependencies core meta-python networking-layer openembedded-layer for layer meta-aws.
93 | DEBUG: Processing dependencies core openembedded-layer for layer meta-python.
94 | DEBUG: Processing dependencies core for layer meta-oe.
95 | DEBUG: Processing dependencies core meta-python openembedded-layer for layer meta-networking.
96 | INFO: Adding layer meta-python
97 | INFO: meta-python is already in /root/dist/meta-aws/qa/checklayer/conf/bblayers.conf
98 | INFO: Adding layer meta-oe
99 | INFO: meta-oe is already in /root/dist/meta-aws/qa/checklayer/conf/bblayers.conf
100 | INFO: Adding layer meta-networking
101 | INFO: meta-networking is already in /root/dist/meta-aws/qa/checklayer/conf/bblayers.conf
102 | INFO: Getting initial bitbake variables ...
103 | INFO: Getting initial signatures ...
104 | INFO: Adding layer meta-aws
105 | INFO: Starting to analyze: meta-aws
106 | INFO: ----------------------------------------------------------------------
107 | INFO: skipped "BSPCheckLayer: Layer meta-aws isn't BSP one."
108 | INFO: test_layerseries_compat (common.CommonCheckLayer)
109 | INFO:  ... ok
110 | INFO: test_parse (common.CommonCheckLayer)
111 | INFO:  ... ok
112 | INFO: test_readme (common.CommonCheckLayer)
113 | INFO:  ... ok
114 | INFO: test_show_environment (common.CommonCheckLayer)
115 | INFO:  ... ok
116 | INFO: test_signatures (common.CommonCheckLayer)
117 | INFO:  ... ok
118 | INFO: test_world (common.CommonCheckLayer)
119 | INFO:  ... ERROR
120 | INFO: Traceback (most recent call last):
121 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 44, in test_world
122 | get_signatures(self.td['builddir'], failsafe=False)
123 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 281, in get_signatures
124 | check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
125 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 256, in check_command
126 | raise RuntimeError(msg)
127 | RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
128 | Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -S none world
129 | Output:
130 | Loading cache...done.
131 | Loaded 3473 entries from dependency cache.
132 | Parsing recipes...done.
133 | Parsing of 2252 .bb files complete (2251 cached, 1 parsed). 3474 targets, 87 skipped, 0 masked, 0 errors.
134 | NOTE: Resolving any missing task queue dependencies
135 | ERROR: Nothing RPROVIDES 'python3-jmespath' (but /root/dist/meta-aws/recipes-devtools/python/python3-botocore_1.20.36.bb, /root/dist/meta-aws/recipes-devtools/python/python3-boto3_1.17.40.bb RDEPENDS on or otherwise requires it)
136 | NOTE: Runtime target 'python3-jmespath' is unbuildable, removing...
137 | Missing or unbuildable dependency chain was: ['python3-jmespath']
138 | ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
139 | Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'python3-botocore', 'python3-jmespath']
140 |  
141 | Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
142 |  
143 |  
144 | INFO: skipped "DistroCheckLayer: Layer meta-aws isn't Distro one."
145 | INFO: ======================================================================
146 | INFO: ERROR: test_world (common.CommonCheckLayer)
147 | INFO: ----------------------------------------------------------------------
148 | INFO: Traceback (most recent call last):
149 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 44, in test_world
150 | get_signatures(self.td['builddir'], failsafe=False)
151 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 281, in get_signatures
152 | check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
153 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 256, in check_command
154 | raise RuntimeError(msg)
155 | RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
156 | Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -S none world
157 | Output:
158 | Loading cache...done.
159 | Loaded 3473 entries from dependency cache.
160 | Parsing recipes...done.
161 | Parsing of 2252 .bb files complete (2251 cached, 1 parsed). 3474 targets, 87 skipped, 0 masked, 0 errors.
162 | NOTE: Resolving any missing task queue dependencies
163 | ERROR: Nothing RPROVIDES 'python3-jmespath' (but /root/dist/meta-aws/recipes-devtools/python/python3-botocore_1.20.36.bb, /root/dist/meta-aws/recipes-devtools/python/python3-boto3_1.17.40.bb RDEPENDS on or otherwise requires it)
164 | NOTE: Runtime target 'python3-jmespath' is unbuildable, removing...
165 | Missing or unbuildable dependency chain was: ['python3-jmespath']
166 | ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
167 | Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'python3-botocore', 'python3-jmespath']
168 |  
169 | Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
170 |  
171 | ----------------------------------------------------------------------
172 | INFO: Ran 6 tests in 641.042s
173 | INFO: FAILED
174 | INFO:  (errors=1, skipped=2)
175 | INFO:
176 | INFO: Summary of results:
177 | INFO:
178 | INFO: meta-aws ... FAIL
179 |  
180 | [Container] 2021/04/02 11:48:48 Command did not exit successfully yocto-check-layer -d -o ycl-check.log --additional-layers meta-python --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python -d $HOME/dist/meta-aws exit status 2
181 | [Container] 2021/04/02 11:48:48 Phase complete: BUILD State: FAILED
182 | [Container] 2021/04/02 11:48:48 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yocto-check-layer -d -o ycl-check.log --additional-layers meta-python --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python -d $HOME/dist/meta-aws. Reason: exit status 2
183 | [Container] 2021/04/02 11:48:48 Entering phase POST_BUILD
184 | [Container] 2021/04/02 11:48:48 Phase complete: POST_BUILD State: SUCCEEDED
185 | [Container] 2021/04/02 11:48:48 Phase context status code:  Message:
186

**Comment by rpcme** [comment]
fixed
