### ISSUE TITLE
Checklayer failure: dunfell: signature changed (need kernel modification opt-in)

### ISSUE THREAD

**Issue by rpcme** [aws/meta-aws#123]
[Container] 2021/04/02 11:54:40 Waiting for agent ping
--
2 | [Container] 2021/04/02 11:54:45 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2021/04/02 11:54:46 Phase is DOWNLOAD_SOURCE
4 | [Container] 2021/04/02 11:54:46 CODEBUILD_SRC_DIR=/codebuild/output/src159671732/src/github.com/aws/meta-aws
5 | [Container] 2021/04/02 11:54:46 YAML location is /codebuild/output/src159671732/src/github.com/aws/meta-aws/qa/buildspec.checklayer.yml
6 | [Container] 2021/04/02 11:54:46 Processing environment variables
7 | [Container] 2021/04/02 11:54:46 No runtime version selected in buildspec.
8 | [Container] 2021/04/02 11:54:46 Run-as user: aws-yocto-builder
9 | [Container] 2021/04/02 11:54:46 Git credential helper enabled
10 | BITBUCKET Git credential unavailable.
11 | GITHUB_ENTERPRISE Git credential unavailable.
12 | [Container] 2021/04/02 11:54:46 Moving to directory /codebuild/output/src159671732/src/github.com/aws/meta-aws
13 | [Container] 2021/04/02 11:54:46 Registering with agent
14 | [Container] 2021/04/02 11:54:46 Phases found in YAML: 2
15 | [Container] 2021/04/02 11:54:46  BUILD: 12 commands
16 | [Container] 2021/04/02 11:54:46  PRE_BUILD: 9 commands
17 | [Container] 2021/04/02 11:54:46 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
18 | [Container] 2021/04/02 11:54:46 Phase context status code:  Message:
19 | [Container] 2021/04/02 11:54:46 Entering phase INSTALL
20 | [Container] 2021/04/02 11:54:46 Phase complete: INSTALL State: SUCCEEDED
21 | [Container] 2021/04/02 11:54:46 Phase context status code:  Message:
22 | [Container] 2021/04/02 11:54:46 Entering phase PRE_BUILD
23 | [Container] 2021/04/02 11:54:46 Run-as user: root
24 | [Container] 2021/04/02 11:54:46 Running command mkdir -p /build-output
25 |  
26 | [Container] 2021/04/02 11:54:46 Running command chown aws-yocto-builder:aws-yocto-builder /build-output
27 |  
28 | [Container] 2021/04/02 11:54:46 Running command chown aws-yocto-builder:aws-yocto-builder /downloads
29 |  
30 | [Container] 2021/04/02 11:54:46 Running command chown aws-yocto-builder:aws-yocto-builder /sstate-cache
31 |  
32 | [Container] 2021/04/02 11:54:46 Running command chmod 777 /build-output
33 |  
34 | [Container] 2021/04/02 11:54:46 Running command chmod 777 /downloads
35 |  
36 | [Container] 2021/04/02 11:54:46 Running command chmod 777 /sstate-cache
37 |  
38 | [Container] 2021/04/02 11:54:46 Running command git config --global user.name "Cloudy Builder"
39 |  
40 | [Container] 2021/04/02 11:54:46 Running command git config --global user.email "email@example.com"
41 |  
42 | [Container] 2021/04/02 11:54:46 Phase complete: PRE_BUILD State: SUCCEEDED
43 | [Container] 2021/04/02 11:54:46 Phase context status code:  Message:
44 | [Container] 2021/04/02 11:54:46 Entering phase BUILD
45 | [Container] 2021/04/02 11:54:46 Running command curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/repo
46 | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
47 | Dload  Upload   Total   Spent    Left  Speed
48 |  
49 | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
50 | 100 43035  100 43035    0     0   712k      0 --:--:-- --:--:-- --:--:--  712k
51 |  
52 | [Container] 2021/04/02 11:54:47 Running command chmod +x $HOME/repo
53 |  
54 | [Container] 2021/04/02 11:54:47 Running command mkdir $HOME/dist
55 |  
56 | [Container] 2021/04/02 11:54:47 Running command cd $HOME/dist
57 |  
58 | [Container] 2021/04/02 11:54:47 Running command $HOME/repo init -u https://github.com/aws/meta-aws -m qa/repo.checklayer.${YP_RELEASE}.xml
59 | Downloading manifest from https://github.com/aws/meta-aws
60 |  
61 | repo has been initialized in /root/dist
62 |  
63 | [Container] 2021/04/02 11:54:49 Running command $HOME/repo sync
64 | repo sync has finished successfully.
65 |  
66 | [Container] 2021/04/02 11:55:15 Running command export PATH=$HOME/dist/poky/scripts:$HOME/dist/poky/bitbake/bin:$PATH
67 |  
68 | [Container] 2021/04/02 11:55:15 Running command export BUILDDIR=$HOME/dist/meta-aws/qa/checklayer
69 |  
70 | [Container] 2021/04/02 11:55:16 Running command export BBPATH=$HOME/dist/meta-aws/qa/checklayer
71 |  
72 | [Container] 2021/04/02 11:55:16 Running command export BB_ENV_EXTRAWHITE=ALL_PROXY BBPATH_EXTRA BB_LOGCONFIG BB_NO_NETWORK BB_NUMBER_THREADS BB_SETSCENE_ENFORCE BB_SRCREV_POLICY DISTRO FTPS_PROXY FTP_PROXY GIT_PROXY_COMMAND HTTPS_PROXY HTTP_PROXY MACHINE NO_PROXY PARALLEL_MAKE SCREENDIR SDKMACHINE SOCKS5_PASSWD SOCKS5_USER SSH_AGENT_PID SSH_AUTH_SOCK STAMPS_DIR TCLIBC TCMODE all_proxy ftp_proxy ftps_proxy http_proxy https_proxy no_proxy
73 |  
74 | [Container] 2021/04/02 11:55:16 Running command sed -i -e "s,DIST,$HOME/dist," -e "s,CODEBUILD_SRC_DIR,${CODEBUILD_SRC_DIR}," $HOME/dist/meta-aws/qa/checklayer/conf/bblayers.conf
75 |  
76 | [Container] 2021/04/02 11:55:16 Running command yocto-check-layer -d -o ycl-check.log --additional-layers meta-python --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python -d $HOME/dist/meta-aws
77 | INFO: Detected layers:
78 | INFO: meta-aws: LayerType.SOFTWARE, /root/dist/meta-aws
79 | ERROR: checklayer: Don't have conf/layer.conf file.
80 | INFO:
81 | INFO: Setting up for meta-aws(LayerType.SOFTWARE), /root/dist/meta-aws
82 | DEBUG: Processing dependencies core for layer meta-aws.
83 | DEBUG: Processing dependencies core for layer meta-aws.
84 | INFO: Getting initial bitbake variables ...
85 | INFO: Getting initial signatures ...
86 | INFO: Adding layer meta-aws
87 | INFO: Starting to analyze: meta-aws
88 | INFO: ----------------------------------------------------------------------
89 | INFO: skipped "BSPCheckLayer: Layer meta-aws isn't BSP one."
90 | INFO: test_layerseries_compat (common.CommonCheckLayer)
91 | INFO:  ... ok
92 | INFO: test_parse (common.CommonCheckLayer)
93 | INFO:  ... ok
94 | INFO: test_readme (common.CommonCheckLayer)
95 | INFO:  ... ok
96 | INFO: test_show_environment (common.CommonCheckLayer)
97 | INFO:  ... ok
98 | INFO: test_signatures (common.CommonCheckLayer)
99 | INFO:  ... FAIL
100 |  
101 | Stdout:
102 | Loading cache...done.
103 | Loaded 3326 entries from dependency cache.
104 | Parsing recipes...done.
105 | Parsing of 2162 .bb files complete (2161 cached, 1 parsed). 3327 targets, 87 skipped, 0 masked, 0 errors.
106 | INFO: Traceback (most recent call last):
107 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 55, in test_signatures
108 | self.fail('Adding layer %s changed signatures.\n%s' % (self.tc.layer['name'], msg))
109 | AssertionError: Adding layer meta-aws changed signatures.
110 | 1464 signatures changed, initial differences (first hash before, second after):
111 | linux-yocto:do_fetch: 337aeeb50e812f42a7669b1ad42057ed2d007c77ae0a7fb799db22723b73af4d -> fc1b394394a493e09350b4f334854decc71130126c07a5d7c507bf0cd57d370f
112 | bitbake-diffsigs --task linux-yocto do_fetch --signature 337aeeb50e812f42a7669b1ad42057ed2d007c77ae0a7fb799db22723b73af4d fc1b394394a493e09350b4f334854decc71130126c07a5d7c507bf0cd57d370f
113 | NOTE: Starting bitbake server...
114 | basehash changed from 90e7b6e2f61bf7cee6cb4ef5aeab46bb6500f619c14e325f819ea4a836c073e1 to b99734f0ccdbb630a639fd6b738d2eb43c5c6c1a30d28ffd6ef54c3f560d2006
115 | Variable SRC_URI value changed:
116 | "git://git.yoctoproject.org/linux-yocto.git;name=machine;branch=${KBRANCH};            git://git.yoctoproject.org/yocto-kernel-cache;type=kmeta;name=meta;branch=yocto-5.4;destsuffix=${KMETA} {+file://linux-kernel.cfg +}"
117 | Dependency on checksum of file linux-kernel.cfg was added
118 |  
119 |  
120 | Stdout:
121 | Loading cache...done.
122 | Loaded 3326 entries from dependency cache.
123 | Parsing recipes...done.
124 | Parsing of 2162 .bb files complete (2161 cached, 1 parsed). 3327 targets, 87 skipped, 0 masked, 0 errors.
125 |  
126 | INFO: test_world (common.CommonCheckLayer)
127 | INFO:  ... ok
128 | INFO: skipped "DistroCheckLayer: Layer meta-aws isn't Distro one."
129 | INFO: ======================================================================
130 | INFO: FAIL: test_signatures (common.CommonCheckLayer)
131 | INFO: ----------------------------------------------------------------------
132 | INFO: Traceback (most recent call last):
133 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 55, in test_signatures
134 | self.fail('Adding layer %s changed signatures.\n%s' % (self.tc.layer['name'], msg))
135 | AssertionError: Adding layer meta-aws changed signatures.
136 | 1464 signatures changed, initial differences (first hash before, second after):
137 | linux-yocto:do_fetch: 337aeeb50e812f42a7669b1ad42057ed2d007c77ae0a7fb799db22723b73af4d -> fc1b394394a493e09350b4f334854decc71130126c07a5d7c507bf0cd57d370f
138 | bitbake-diffsigs --task linux-yocto do_fetch --signature 337aeeb50e812f42a7669b1ad42057ed2d007c77ae0a7fb799db22723b73af4d fc1b394394a493e09350b4f334854decc71130126c07a5d7c507bf0cd57d370f
139 | NOTE: Starting bitbake server...
140 | basehash changed from 90e7b6e2f61bf7cee6cb4ef5aeab46bb6500f619c14e325f819ea4a836c073e1 to b99734f0ccdbb630a639fd6b738d2eb43c5c6c1a30d28ffd6ef54c3f560d2006
141 | Variable SRC_URI value changed:
142 | "git://git.yoctoproject.org/linux-yocto.git;name=machine;branch=${KBRANCH};            git://git.yoctoproject.org/yocto-kernel-cache;type=kmeta;name=meta;branch=yocto-5.4;destsuffix=${KMETA} {+file://linux-kernel.cfg +}"
143 | Dependency on checksum of file linux-kernel.cfg was added
144 |  
145 |  
146 | Stdout:
147 | Loading cache...done.
148 | Loaded 3326 entries from dependency cache.
149 | Parsing recipes...done.
150 | Parsing of 2162 .bb files complete (2161 cached, 1 parsed). 3327 targets, 87 skipped, 0 masked, 0 errors.
151 | ----------------------------------------------------------------------
152 | INFO: Ran 6 tests in 922.877s
153 | INFO: FAILED
154 | INFO:  (failures=1, skipped=2)
155 | INFO:
156 | INFO: Summary of results:
157 | INFO:
158 | INFO: meta-aws ... FAIL
159 |  
160 | [Container] 2021/04/02 12:18:57 Command did not exit successfully yocto-check-layer -d -o ycl-check.log --additional-layers meta-python --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python -d $HOME/dist/meta-aws exit status 2
161 | [Container] 2021/04/02 12:18:57 Phase complete: BUILD State: FAILED
162 | [Container] 2021/04/02 12:18:57 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yocto-check-layer -d -o ycl-check.log --additional-layers meta-python --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python -d $HOME/dist/meta-aws. Reason: exit status 2
163 | [Container] 2021/04/02 12:18:57 Entering phase POST_BUILD
164 | [Container] 2021/04/02 12:18:57 Phase complete: POST_BUILD State: SUCCEEDED
165 | [Container] 2021/04/02 12:18:57 Phase context status code:  Message:

**Comment by rpcme** [comment]
fixed
