### ISSUE TITLE
Checklayer failure: zeus: multiple check failures (no opt-ins for kernel, docker patch not guarded, more)

### ISSUE THREAD

**Issue by rpcme** [aws/meta-aws#124]
[Container] 2021/04/02 12:34:44 Waiting for agent ping
--
2 | [Container] 2021/04/02 12:34:47 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2021/04/02 12:34:48 Phase is DOWNLOAD_SOURCE
4 | [Container] 2021/04/02 12:34:48 CODEBUILD_SRC_DIR=/codebuild/output/src646616690/src/github.com/aws/meta-aws
5 | [Container] 2021/04/02 12:34:48 YAML location is /codebuild/output/src646616690/src/github.com/aws/meta-aws/qa/buildspec.checklayer.yml
6 | [Container] 2021/04/02 12:34:48 Processing environment variables
7 | [Container] 2021/04/02 12:34:48 No runtime version selected in buildspec.
8 | [Container] 2021/04/02 12:34:48 Run-as user: aws-yocto-builder
9 | [Container] 2021/04/02 12:34:48 Git credential helper enabled
10 | BITBUCKET Git credential unavailable.
11 | GITHUB_ENTERPRISE Git credential unavailable.
12 | [Container] 2021/04/02 12:34:48 Moving to directory /codebuild/output/src646616690/src/github.com/aws/meta-aws
13 | [Container] 2021/04/02 12:34:48 Registering with agent
14 | [Container] 2021/04/02 12:34:48 Phases found in YAML: 2
15 | [Container] 2021/04/02 12:34:48  PRE_BUILD: 9 commands
16 | [Container] 2021/04/02 12:34:48  BUILD: 12 commands
17 | [Container] 2021/04/02 12:34:48 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
18 | [Container] 2021/04/02 12:34:48 Phase context status code:  Message:
19 | [Container] 2021/04/02 12:34:48 Entering phase INSTALL
20 | [Container] 2021/04/02 12:34:48 Phase complete: INSTALL State: SUCCEEDED
21 | [Container] 2021/04/02 12:34:48 Phase context status code:  Message:
22 | [Container] 2021/04/02 12:34:48 Entering phase PRE_BUILD
23 | [Container] 2021/04/02 12:34:48 Run-as user: root
24 | [Container] 2021/04/02 12:34:48 Running command mkdir -p /build-output
25 |  
26 | [Container] 2021/04/02 12:34:48 Running command chown aws-yocto-builder:aws-yocto-builder /build-output
27 |  
28 | [Container] 2021/04/02 12:34:48 Running command chown aws-yocto-builder:aws-yocto-builder /downloads
29 |  
30 | [Container] 2021/04/02 12:34:48 Running command chown aws-yocto-builder:aws-yocto-builder /sstate-cache
31 |  
32 | [Container] 2021/04/02 12:34:48 Running command chmod 777 /build-output
33 |  
34 | [Container] 2021/04/02 12:34:48 Running command chmod 777 /downloads
35 |  
36 | [Container] 2021/04/02 12:34:48 Running command chmod 777 /sstate-cache
37 |  
38 | [Container] 2021/04/02 12:34:48 Running command git config --global user.name "Cloudy Builder"
39 |  
40 | [Container] 2021/04/02 12:34:48 Running command git config --global user.email "email@example.com"
41 |  
42 | [Container] 2021/04/02 12:34:48 Phase complete: PRE_BUILD State: SUCCEEDED
43 | [Container] 2021/04/02 12:34:48 Phase context status code:  Message:
44 | [Container] 2021/04/02 12:34:48 Entering phase BUILD
45 | [Container] 2021/04/02 12:34:48 Running command curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/repo
46 | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
47 | Dload  Upload   Total   Spent    Left  Speed
48 |  
49 | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
50 | 100 43035  100 43035    0     0  1827k      0 --:--:-- --:--:-- --:--:-- 1827k
51 |  
52 | [Container] 2021/04/02 12:34:49 Running command chmod +x $HOME/repo
53 |  
54 | [Container] 2021/04/02 12:34:49 Running command mkdir $HOME/dist
55 |  
56 | [Container] 2021/04/02 12:34:49 Running command cd $HOME/dist
57 |  
58 | [Container] 2021/04/02 12:34:49 Running command $HOME/repo init -u https://github.com/aws/meta-aws -m qa/repo.checklayer.${YP_RELEASE}.xml
59 | Downloading manifest from https://github.com/aws/meta-aws
60 |  
61 | repo has been initialized in /root/dist
62 |  
63 | [Container] 2021/04/02 12:34:51 Running command $HOME/repo sync
64 | repo sync has finished successfully.
65 |  
66 | [Container] 2021/04/02 12:35:16 Running command export PATH=$HOME/dist/poky/scripts:$HOME/dist/poky/bitbake/bin:$PATH
67 |  
68 | [Container] 2021/04/02 12:35:16 Running command export BUILDDIR=$HOME/dist/meta-aws/qa/checklayer
69 |  
70 | [Container] 2021/04/02 12:35:16 Running command export BBPATH=$HOME/dist/meta-aws/qa/checklayer
71 |  
72 | [Container] 2021/04/02 12:35:16 Running command export BB_ENV_EXTRAWHITE=ALL_PROXY BBPATH_EXTRA BB_LOGCONFIG BB_NO_NETWORK BB_NUMBER_THREADS BB_SETSCENE_ENFORCE BB_SRCREV_POLICY DISTRO FTPS_PROXY FTP_PROXY GIT_PROXY_COMMAND HTTPS_PROXY HTTP_PROXY MACHINE NO_PROXY PARALLEL_MAKE SCREENDIR SDKMACHINE SOCKS5_PASSWD SOCKS5_USER SSH_AGENT_PID SSH_AUTH_SOCK STAMPS_DIR TCLIBC TCMODE all_proxy ftp_proxy ftps_proxy http_proxy https_proxy no_proxy
73 |  
74 | [Container] 2021/04/02 12:35:16 Running command sed -i -e "s,DIST,$HOME/dist," -e "s,CODEBUILD_SRC_DIR,${CODEBUILD_SRC_DIR}," $HOME/dist/meta-aws/qa/checklayer/conf/bblayers.conf
75 |  
76 | [Container] 2021/04/02 12:35:16 Running command yocto-check-layer -d -o ycl-check.log --additional-layers meta-python --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python -d $HOME/dist/meta-aws
77 | INFO: Detected layers:
78 | INFO: meta-aws: LayerType.SOFTWARE, /root/dist/meta-aws
79 | ERROR: checklayer: Don't have conf/layer.conf file.
80 | INFO:
81 | INFO: Setting up for meta-aws(LayerType.SOFTWARE), /root/dist/meta-aws
82 | DEBUG: Processing dependencies core for layer meta-aws.
83 | DEBUG: Processing dependencies core for layer meta-aws.
84 | INFO: Getting initial bitbake variables ...
85 | INFO: Getting initial signatures ...
86 | INFO: Adding layer meta-aws
87 | INFO: Starting to analyze: meta-aws
88 | INFO: ----------------------------------------------------------------------
89 | INFO: skipped "BSPCheckLayer: Layer meta-aws isn't BSP one."
90 | INFO: test_layerseries_compat (common.CommonCheckLayer)
91 | INFO:  ... ok
92 | INFO: test_parse (common.CommonCheckLayer)
93 | INFO:  ... ERROR
94 | INFO: Traceback (most recent call last):
95 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
96 | check_command('Layer %s failed to parse.' % self.tc.layer['name'],
97 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 234, in check_command
98 | raise RuntimeError(msg)
99 | RuntimeError: Layer meta-aws failed to parse.
100 | Command: bitbake -p
101 | Output:
102 | Parsing recipes...done.
103 | ERROR: No recipes available for:
104 | /root/dist/meta-aws/recipes-containers/docker/docker-ce_%.bbappend
105 | Parsing of 2308 .bb files complete (0 cached, 2308 parsed). 3499 targets, 80 skipped, 0 masked, 0 errors.
106 |  
107 | Summary: There was 1 ERROR message shown, returning a non-zero exit code.
108 |  
109 |  
110 | INFO: test_readme (common.CommonCheckLayer)
111 | INFO:  ... ok
112 | INFO: test_show_environment (common.CommonCheckLayer)
113 | INFO:  ... ok
114 | INFO: test_signatures (common.CommonCheckLayer)
115 | INFO:  ... ERROR
116 | INFO: Traceback (most recent call last):
117 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 52, in test_signatures
118 | curr_sigs, _ = get_signatures(self.td['builddir'], failsafe=True)
119 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 259, in get_signatures
120 | check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
121 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 234, in check_command
122 | raise RuntimeError(msg)
123 | RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
124 | Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -k -S none world
125 | Output:
126 | Loading cache...done.
127 | Loaded 3498 entries from dependency cache.
128 | Parsing recipes...done.
129 | ERROR: No recipes available for:
130 | /root/dist/meta-aws/recipes-containers/docker/docker-ce_%.bbappend
131 | Parsing of 2308 .bb files complete (2307 cached, 1 parsed). 3499 targets, 80 skipped, 0 masked, 0 errors.
132 |  
133 | Summary: There was 1 ERROR message shown, returning a non-zero exit code.
134 |  
135 |  
136 | INFO: test_world (common.CommonCheckLayer)
137 | INFO:  ... ERROR
138 | INFO: Traceback (most recent call last):
139 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 44, in test_world
140 | get_signatures(self.td['builddir'], failsafe=False)
141 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 259, in get_signatures
142 | check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
143 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 234, in check_command
144 | raise RuntimeError(msg)
145 | RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
146 | Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -S none world
147 | Output:
148 | Loading cache...done.
149 | Loaded 3498 entries from dependency cache.
150 | Parsing recipes...done.
151 | ERROR: No recipes available for:
152 | /root/dist/meta-aws/recipes-containers/docker/docker-ce_%.bbappend
153 | Parsing of 2308 .bb files complete (2307 cached, 1 parsed). 3499 targets, 80 skipped, 0 masked, 0 errors.
154 |  
155 | Summary: There was 1 ERROR message shown, returning a non-zero exit code.
156 |  
157 |  
158 | INFO: skipped "DistroCheckLayer: Layer meta-aws isn't Distro one."
159 | INFO: ======================================================================
160 | INFO: ERROR: test_parse (common.CommonCheckLayer)
161 | INFO: ----------------------------------------------------------------------
162 | INFO: Traceback (most recent call last):
163 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
164 | check_command('Layer %s failed to parse.' % self.tc.layer['name'],
165 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 234, in check_command
166 | raise RuntimeError(msg)
167 | RuntimeError: Layer meta-aws failed to parse.
168 | Command: bitbake -p
169 | Output:
170 | Parsing recipes...done.
171 | ERROR: No recipes available for:
172 | /root/dist/meta-aws/recipes-containers/docker/docker-ce_%.bbappend
173 | Parsing of 2308 .bb files complete (0 cached, 2308 parsed). 3499 targets, 80 skipped, 0 masked, 0 errors.
174 |  
175 | Summary: There was 1 ERROR message shown, returning a non-zero exit code.
176 |  
177 | ======================================================================
178 | INFO: ERROR: test_signatures (common.CommonCheckLayer)
179 | INFO: ----------------------------------------------------------------------
180 | INFO: Traceback (most recent call last):
181 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 52, in test_signatures
182 | curr_sigs, _ = get_signatures(self.td['builddir'], failsafe=True)
183 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 259, in get_signatures
184 | check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
185 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 234, in check_command
186 | raise RuntimeError(msg)
187 | RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
188 | Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -k -S none world
189 | Output:
190 | Loading cache...done.
191 | Loaded 3498 entries from dependency cache.
192 | Parsing recipes...done.
193 | ERROR: No recipes available for:
194 | /root/dist/meta-aws/recipes-containers/docker/docker-ce_%.bbappend
195 | Parsing of 2308 .bb files complete (2307 cached, 1 parsed). 3499 targets, 80 skipped, 0 masked, 0 errors.
196 |  
197 | Summary: There was 1 ERROR message shown, returning a non-zero exit code.
198 |  
199 | ======================================================================
200 | INFO: ERROR: test_world (common.CommonCheckLayer)
201 | INFO: ----------------------------------------------------------------------
202 | INFO: Traceback (most recent call last):
203 | File "/root/dist/poky/scripts/lib/checklayer/cases/common.py", line 44, in test_world
204 | get_signatures(self.td['builddir'], failsafe=False)
205 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 259, in get_signatures
206 | check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
207 | File "/root/dist/poky/scripts/lib/checklayer/__init__.py", line 234, in check_command
208 | raise RuntimeError(msg)
209 | RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
210 | Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -S none world
211 | Output:
212 | Loading cache...done.
213 | Loaded 3498 entries from dependency cache.
214 | Parsing recipes...done.
215 | ERROR: No recipes available for:
216 | /root/dist/meta-aws/recipes-containers/docker/docker-ce_%.bbappend
217 | Parsing of 2308 .bb files complete (2307 cached, 1 parsed). 3499 targets, 80 skipped, 0 masked, 0 errors.
218 |  
219 | Summary: There was 1 ERROR message shown, returning a non-zero exit code.
220 |  
221 | ----------------------------------------------------------------------
222 | INFO: Ran 6 tests in 152.263s
223 | INFO: FAILED
224 | INFO:  (errors=3, skipped=2)
225 | INFO:
226 | INFO: Summary of results:
227 | INFO:
228 | INFO: meta-aws ... FAIL
229 |  
230 | [Container] 2021/04/02 12:45:57 Command did not exit successfully yocto-check-layer -d -o ycl-check.log --additional-layers meta-python --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python -d $HOME/dist/meta-aws exit status 2
231 | [Container] 2021/04/02 12:45:57 Phase complete: BUILD State: FAILED
232 | [Container] 2021/04/02 12:45:57 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yocto-check-layer -d -o ycl-check.log --additional-layers meta-python --dependency $HOME/dist/meta-openembedded/meta-oe $HOME/dist/meta-openembedded/meta-networking $HOME/dist/meta-openembedded/meta-python -d $HOME/dist/meta-aws. Reason: exit status 2
233 | [Container] 2021/04/02 12:45:57 Entering phase POST_BUILD
234 | [Container] 2021/04/02 12:45:57 Phase complete: POST_BUILD State: SUCCEEDED
235 | [Container] 2021/04/02 12:45:57 Phase context status code:  Message:

**Comment by rpcme** [comment]
This has been fixed.
